FROM ruby:2.5.1

RUN apt-get update && apt-get install -y nodejs && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . /usr/src/app
RUN bundle install
COPY . /usr/src/app

CMD ["bundle", "exec", "middleman", "build"]
