@startuml
"Investment Manager" --> Bank: Send funds
Bank --> "Goji Platform": Funds arrived
"Investment Manager" --> "Goji Platform": Record repayment
"Goji Platform" --> "Investment Manager": success
"Goji Platform" --> "Goji Platform": Update investor records
"Goji Platform" --> "Investment Manager": Tax & Fees returned to payment destination
@enduml