apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: apidoc
  labels:
    app.kubernetes.io/name: apidoc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apidoc
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
